### ISSUE TITLE
Pasting a url into the custom url box will open an instance of chrome. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-android#161] opened 2021-03-03 15:11 UTC
Using a text editor on android. Type out your instance url and copy it. 
Install the android app. 
Launch the app
Tap custom instance
Hold on the url field. 
Tap paste
Tap save
The app opens an instance of chrome instead of within the app. 

This occurs on both the webview and xwalk versions.

**Comment by garethbowen** [comment] 2021-03-03 17:54
Does it happen if you type it out by hand?

**Comment by newtewt** [comment] 2021-03-03 17:56
@garethbowen  that is the workaround.  Typing it and then hitting save works fine.

**Comment by mrsarm** [comment] 2021-11-25 11:42
I couldn't reproduce this error on Android 10 an 11 (Webview) and Android 6 (Crosswalk), and the behavior described never happened to me in the past, were several times I copy & pasted the URL in the app to test other issues, so closing for now, but if anyone experience the same fill free to reopen.

**Closed by mrsarm** 2021-11-25 11:42 UTC
Labels: Type: Bug
