### ISSUE TITLE
Support Android 14

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#332] opened 2023-10-06 02:47 UTC
This is required for any app wanting to publish to the app store after August. We should do this early so project apps don't get blocked or have to be updated last minute (like we did [last time](#324)).

- [ ] Check out what's new: https://developer.android.com/about/versions/14
- [ ] Update target sdk to 34

**Comment by latin-panda** [comment] 2023-10-26 06:32
The PlayStore deadline for this upgrade hasn't been announced yet but based on previous experiences maybe it's going to be around September or October of 2024. Keep an eye [here](https://developer.android.com/distribute/play-policies) for the announcement. 

cc: @michaelkohn

**Comment by jkuester** [comment] 2024-02-08 11:46
We have a partner now that is running into issues with cht-android on Android 14 devices in production.  We are in the process of doing some testing and collecting more information, but the initial error dialog that gets shown on the device says:

> This app isn't compatible with the latest version of Android. Check for an update or contact the app's developer.

@Kymoraa please feel free to add any additional information you have to this thread!  It would be especially good to get some details about:

- Type of device
- Version of cht-android

Thank you!

**Comment by Kymoraa** [comment] 2024-02-13 10:01
> We have a partner now that is running into issues with cht-android on Android 14 devices in production. We are in the process of doing some testing and collecting more information, but the initial error dialog that gets shown on the device says:
> 
> > This app isn't compatible with the latest version of Android. Check for an update or contact the app's developer.
> 
> @Kymoraa please feel free to add any additional information you have to this thread! It would be especially good to get some details about:
> 
> * Type of device
> * Version of cht-android
> 
> Thank you!

Hello @jkuester,

Together with Robert, we were not able to replicate the issue on a physical device that was upgraded to Android 14. We installed the Vihiga APK and were able to log in successfully. However, the issue is being experienced and reported by stakeholders in the field. I am yet to get the numbers and device details (I'll add to the comments when I get them) but I am attaching a video I've just received from the team. 

Below is a eCHIS APK. eCHIS is on CHT v3.13 and the cht-android is v1.0.1 _(The same has also been reported for Vihiga which is on v4.x)_

https://github.com/medic/cht-android/assets/3049987/59de31bd-50a5-4956-aa80-98ed7922ccc8

![IMG_20240207_214822](https://github.com/medic/cht-android/assets/3049987/da437da9-34d6-41ea-83a3-8159ae3a87c9)

**Comment by Kymoraa** [comment] 2024-02-13 12:30
The device above: 
```
Samsung Galaxy Tab A7 Lite.
Model is SM-225N.
```

**Comment by jkuester** [comment] 2024-03-13 14:58
Just want to note here that @Kymoraa has confirmed that the errors documented in this thread were resolved by the code changes in https://github.com/medic/cht-android/pull/349!  :tada:   The goal is to get these changes reviewed/merged/released as soon as possible so folks can start rolling out new APK versions.

**Closed** 2024-03-15 19:40 UTC
Labels: Type: Improvement
